### ISSUE TITLE
BeforePlaybackEvent does not happen before playback

### ISSUE THREAD

**Issue by tylercollier** [php-vcr/php-vcr#101]
Kudos to @aaa2000 who added hooks on #86.

The BeforePlaybackEvent does not actually happen before playback. Look at `Videorecorder.php`:

```
public function handleRequest(Request $request)
{
    ...
    if ($this->cassette->hasResponse($request)) {
        $this->dispatch(VCREvents::VCR_BEFORE_PLAYBACK, new BeforePlaybackEvent($request, $this->cassette));
        $response = $this->cassette->playback($request);
        $this->dispatch(VCREvents::VCR_AFTER_PLAYBACK, new AfterPlaybackEvent($request, $response, $this->cassette));
```

`hasResponse` just calls `playback`. Thus, the code should look more like this:

```
$this->dispatch(VCREvents::VCR_BEFORE_PLAYBACK, new BeforePlaybackEvent($request, $this->cassette));
if ($this->cassette->hasResponse($request)) {
    $response = $this->cassette->playback($request);
    $this->dispatch(VCREvents::VCR_AFTER_PLAYBACK, new AfterPlaybackEvent($request, $response, $this->cassette));
    ...
```

This feels gross, but is more correct.

So, how to fix the grossness of dispatching the event before the `if`? Some ideas:
* Dispatch the VCR_BEFORE_PLAYBACK event in the actual `playback` method. This means the event would be dispatched each time playback happens. That might be what's wanted. If not, we could keep track if the event has already been dispatched.
* Why is `playback` responsible for finding a response? Doesn't that make more sense for `hasResponse` to do? Or really, I think the code that does the work of finding find the response should be moved from `playback` into a `getResponse` method, which is called both from `hasResponse` and `playback`.

I'm happy to do any of this work. Just asking for input first.

**Comment by tylercollier** [comment]
Here's my motivation if it matters.

I am using Guzzle, which sets the User-Agent header to be something like

    User-Agent: 'Guzzle/3.9.2 curl/7.22.0 PHP/5.4.23'

The problem with this is that that's MY version of curl and PHP. If another developer has a different version, the request won't match. This scenario is happening on my team.

So my VCR_BEFORE_PLAYBACK hook strips the User-Agent header if it finds version numbers in it.

But this is why the BEFORE_PLAYBACK hook must actually run earlier than it currently does.

**Comment by adri** [comment]
Yes you are right, good point. We could move the content of the if above and then check the response. 
This a nice side effect: Because `hasRequest` calls `playback`, `playback` is actually called twice which should be changed for a speedup like shown in #93. 

How do you like something like this?

```
$this->dispatch(VCREvents::VCR_BEFORE_PLAYBACK, new BeforePlaybackEvent($request, $this->cassette));
$response = $this->cassette->playback($request); // or getRequest()
$this->dispatch(VCREvents::VCR_AFTER_PLAYBACK, new AfterPlaybackEvent($request, $response, $this->cassette));

if ($response) {
   return $response;
}
```

**Comment by tylercollier** [comment]
That's fine. It gets the job done. I prefer my idea; separating out concepts like 'match request' and 'playback request' gives you more flexibility.

This solution always dispatches the `AFTER_PLAYBACK` event, even if there was no playback. I don't have a use case for such an event, so I can't think if one way is better than the other. I'm not sure if anyone would, but if they e.g. opened a connection somewhere in `BEFORE_PLAYBACK`, they'd want to tear that connection down in `AFTER_PLAYBACK`. I suppose you could pass the response in the `AFTER_PLAYBACK` event, and then the callback could decide to continue or not.

**Comment by aaa2000** [comment]
Sorry for the bug and sorry for the late reply.

I didn't know ruby but after looking at the vcr code https://github.com/vcr/vcr/blob/e1f8dec6d5a2b254fba24c36933150d50d7b869b/lib/vcr/cassette.rb#L173. 
and read again the cucumber feature https://www.relishapp.com/vcr/vcr/v/2-9-3/docs/hooks/before-playback-hook, I think I misunderstood the ```BEFORE_PLAYBACK``` event in vcr.  It seems to me that the event should be on all HTTP interactions in the cassette and not on the current request.

If the difference between vcr and php-vcr is not important for you, I could send a pull request with https://github.com/php-vcr/php-vcr/issues/101#issuecomment-73141568 or moving the event dispatching in the Cassette::playback method

**Comment by tylercollier** [comment]
@aaa2000 The pull request as you suggest would be great!

**Comment by tylercollier** [comment]
@aaa2000 I want this ASAP so I have started it, but don't want to step on your toes. Let me know if you're presently working on it.

@aaa2000 & @adri, your advice/opinions would helpful for the following:
* I figured it would be better to follow Ruby VCR's lead, as aaa2000 mentioned, and dispatch the 'before playback' event for each http interaction in the cassette. The new behavior is different, so how do we alert library PHP-VCR users?
* Ruby VCR doesn't have an "after playback" event, but we do. I suppose that should also be per http interaction, mirroring before playback.
* I am thinking of moving the event dispatch stuff into the configuration, a la Ruby VCR. That makes it easier to dispatch events from anywhere.

**Comment by aaa2000** [comment]
@tylercollier I send a PR with the https://github.com/php-vcr/php-vcr/issues/101#issuecomment-73141568

But the fix is strange because now when the cassette has no response, the VCR_BEFORE_PLAYBACK and VCR_AFTER_PLAYBACK are dispatched. I don't like it.

Maybe, it is better to introduce another event VCR_BEFORE_REPLAY to the new behavior and deprecated the VCR_BEFORE_PLAYBACK. We can alert the user via 

```
trigger_error('The VCR_BEFORE_PLAYBACK event is deprecated since version 1.x and will be removed in 2.0. You should use the VCR_BEFORE_REPLAY event instead.', E_USER_DEPRECATED);
```

**Comment by tylercollier** [comment]
@aaa2000 I liked your suggestion to follow Ruby and dispatch the "before playback" event for each http interaction. I submitted a PR with my attempt.

**Comment by adri** [comment]
While working on this I realised a few things.

1. The motivation for this change is request matching. 

    > The problem with this is that that's MY version of curl and PHP. If another developer has a different version, the request won't match. This scenario is happening on my team.
> So my VCR_BEFORE_PLAYBACK hook strips the User-Agent header if it finds version numbers in it.

    This would be related to request matching. @tylercollier the way you handled it, is perfectly fine. I believe requests should not be rewritten for the purpose of matching it properly. That's what request matchers are there for. 

2. We still didn't understand how it is in vcr (ruby) 

    While digging through the source code and tests I found [the following](https://www.relishapp.com/vcr/vcr/v/2-9-3/docs/hooks/before-playback-hook):

    > The `before_playback` hook is called before a cassette sets up its stubs for playback.

    So actually the `before_playback` hook is dispatched **once** for every interaction (request/response pair) of a cassette. In the code it is the [`||=` on this line](https://github.com/vcr/vcr/blob/master/lib/vcr/cassette.rb#L174) which only executes the `.tap` if the class property is not initialised yet. Note, that this is not at all related to every new request. 

    One usecase of this event is to ignore certain interactions:
   > You can also call #ignore! on the HTTP interaction to prevent VCR from playing it back.

    Would that be a usecase that is important to anyone? 

---

I agree that this needs cleaning up though. `VCR_BEFORE_PLAYBACK` should be fired in any case. But firing the `VCR_AFTER_PLAYBACK` event in any case doesn't make much sense and should be limited to only when there has been a playback (= request was found and response is played back). This would be the solution that I would implement...

```php
$event = new BeforePlaybackEvent($request, $this->cassette);
$this->dispatch(VCREvents::VCR_BEFORE_PLAYBACK, $event);

// Find a suitable response in the cassette.
$response = $this->cassette->playback($request);

// Playback succeeded and the recorded response can be returned.
if (!empty($response)) {
    $event = new AfterPlaybackEvent($request, $response, $this->cassette);
    $this->dispatch(VCREvents::VCR_AFTER_PLAYBACK, $event);

    return $response;
}
```

`hasResponse()` is then gone which leads to a nice performance boost. 
@aaa2000 This way we don't break the VCRBundle and don't issue a `VCR_AFTER_PLAYBACK` with a null response.

**Comment by aaa2000** [comment]
for me it is good
