### ISSUE TITLE
doc improvement

### ISSUE THREAD

**Issue by dbu** [php-vcr/php-vcr#104]
we got an error from the symfony YamlParser that the yaml is invalid. trying to run a yaml-linter managed to output the actual reason which was that the nesting for pcre got too deep. the problem is fixed by increasing `pcre.backtrack_limit` in php.ini

probably would also be fixed by switching to store fixtures in json.

do you have an FAQ or troubleshooting section somewhere where i could add this bit of info?

**Comment by adri** [comment]
Mh imo the best would be to extend the current documentation on the website. The website is hosted on github https://github.com/php-vcr/php-vcr.github.io.

I wonder if it should go into the `Installation` part or another FAQ section https://github.com/php-vcr/php-vcr.github.io/tree/master/documentation/_posts.

**Comment by adri** [comment]
Added to documentation http://php-vcr.github.io/documentation/configuration/#storage thanks to @aaa2000.

**Comment by gerrywastaken** [comment]
@adri Do we know the section of code that is segfaulting? Is it possible to catch this before the segfault or handle the problem in graceful way that alerts the user to the issue?

**Comment by aaa2000** [comment]
I don't think It can be handle in graceful way. At the time, I had found that https://bugs.php.net/bug.php?id=40846
