### ISSUE TITLE
url_stat should handle a second param $flags

### ISSUE THREAD

**Issue by dbu** [php-vcr/php-vcr#108]
Stream::url_stat has a second parameter $flags that would tell whether we want to resolve symlinks or not. we should probably handle this parameter in StreamProcessor. No idea what the right thing to do would be, unfortunately.

I just know that when we have a symlinked folder, is_link still returns false, making e.g. the symfony Filesystem::remove try to delete a folder instead of removing the symlink.

We tried some stuff in #106 but that was a series of misunderstandings. No idea what should be done for proper behaviour.

**Comment by dbu** [comment]
probably we should call [lstat](http://php.net/lstat) instead when STREAM_URL_STAT_LINK is set.

not sure if we really want to respect STREAM_URL_STAT_QUIET to supress errors or trigger_error on errors.

**Comment by adri** [comment]
I stole this class (as mentioned somewhere in the docs) from here:
https://github.com/antecedent/patchwork/blob/master/src/Preprocessor/Stream.php

It seems to be an issue and maybe this will help:
https://github.com/antecedent/patchwork/commit/4310769f47e45abcb0bb621360024f7c4126fe62

**Comment by dbu** [comment]
hm, i think @antecedent will have a problem with symlinks in his project. @antecedent did you ever check if is_link still works when the patchwork pre processor is loaded?

we should port that change you link and then add the lstat case. will see if i get to it.
