### ISSUE TITLE
Not wrapping around SSL sockets?

### ISSUE THREAD

**Issue by morrislaptop** [php-vcr/php-vcr#109]
Using the [mindscape/raygun4php](https://github.com/MindscapeHQ/raygun4php) library, I'm trying to test the calls this library is making.

However it looks like it is making a call like:

``` php
$fp = stream_socket_client('ssl://api.raygun.io:443', $err, $errstr, 10, STREAM_CLIENT_CONNECT, $context);
```

And VCR isn't picking it up. I tried `stream_wrapper_register('ssl', __CLASS__, STREAM_IS_URL);` but got a load of errors and thought you might know better ;)

**Comment by adri** [comment]
Hey,

it seems like raygun4php is either calling

 1.  [curl on the command line](https://github.com/MindscapeHQ/raygun4php/blob/master/src/Raygun4php/RaygunClient.php#L316) for which there is basically no chance to intercept it or   
 2. [building a HTTP request themselves](https://github.com/MindscapeHQ/raygun4php/blob/master/src/Raygun4php/RaygunClient.php#L326) and send it via a socket. 

I wonder what the reasons were to implement it like this @fundead. At the moment PHP-VCR can't intercept socket functions like `fsockopen` or `stream_socket_client`. What is sent over the socket doesn't necessarily need to be a HTTP request. I guess it can be done by intercepting `stream_socket_client` and returning a "fake" resource which can be written to. 
At the moment I'm too busy to implement this myself but I'm happy about pull requests implementing it ;-)

**Comment by morrislaptop** [comment]
If debug mode is off it doesn't wait for the response (async-ish) so that error reporting is faster. 

Hah I'll give it a crack and see how I go, no promises!

**Comment by adri** [comment]
@morrislaptop Did you manage to have some progress in this by any chance?

**Comment by morrislaptop** [comment]
Nope ;) https://github.com/morrislaptop/error-tracker-adapter/blob/master/tests/Adapter/RaygunTest.php

**Comment by JeroenVanOort** [comment]
I'm closing this, since it no longer seems to be a problem.
