### ISSUE TITLE
Curl getinfo not stored

### ISSUE THREAD

**Issue by dbu** [php-vcr/php-vcr#112]
curl getinfo is not recorded. when replaying, i end up with "Not implemented: CURLINFO_EFFECTIVE_URL (1048577)" - maybe we should have an option to activate recording this information. Not sure if it should be on by default, its quite heavy and often not relevant.

**Comment by JeroenVanOort** [comment]
I'm closing this issue because it has not seen any activity for many years. If anyone feels this is still a problem, please open a new issue.
