### ISSUE TITLE
Integrate use of drupal_http_request

### ISSUE THREAD

**Issue by jacobbednarz** [php-vcr/php-vcr#114]
Hey,
I am trying to use PHP VCR with Drupal's [`drupal_http_request()`](https://api.drupal.org/api/drupal/includes%21common.inc/function/drupal_http_request/7) however I cannot seem to get it to write the cassette - however works fine with PHP's `file_get_contents`.

Are you able to have a look and let me know where this could be going wrong or how I would look at patching it so that it can be used?

Thanks!

**Comment by adri** [comment]
Thanks, seems to be related to #109.

**Comment by adri** [comment]
Drupals [`drupal_http_request()`](https://api.drupal.org/api/drupal/includes%21common.inc/function/drupal_http_request/7) uses  `stream_socket_client` to create a tcp socket connection and builds its own HTTP request. Like described in #109 it is possible to intercept this but I don't have the time to do it.

In Drupal 8 you can use [`Drupal::httpClient()`](https://api.drupal.org/api/drupal/core!lib!Drupal.php/function/Drupal%3A%3AhttpClient/8) to get a Guzzle instance, that should work fine.

**Comment by adri** [comment]
I'll close this issue in favour of #109.

**Comment by adri** [comment]
@jacobbednarz  Btw, what are you trying to do? Are you testing Drupal modules?

**Comment by jacobbednarz** [comment]
yep - Drupal modules and a custom lightweight API layer which I wrote about at http://jacobbednarz.github.io/posts/lightweight-rest-api-with-drupal/

**Comment by adri** [comment]
I think if you want performance it could make sense to use a tool made for this. See also http://drupal.stackexchange.com/questions/38394/using-javascript-frameworks-like-backbone-with-drupal#39393

**Comment by jacobbednarz** [comment]
Thanks for the feedback @adri. 

While it's a bit off topic, we rolled a custom lightweight API layer as we also run a service orientated architecture where most of the functionality is consumed outside of Drupal (so front end frameworks are no use). Additionally, most of the time the internals included too many components we weren't going to use (such as the theme layer) and added precious ms to our response time. We got around this by bootstrapping at a lower point and not waiting for those extra parts to load - which is something a front end framework couldn't do.

**Comment by adri** [comment]
Sorry for my unconsolidated feedback ;-) I just went through optimising a Drupal site using a similar approach and felt like sharing. Using HHVM sped up considerably and lowered the used resources btw.

PS: The answer in the link is more about using node or other technology instead of frontend frameworks.

**Comment by jacobbednarz** [comment]
Not a problem at all! Appreciate the feedback and will keep it in mind. 😊
