### ISSUE TITLE
Incompatibility with requests library

### ISSUE THREAD

**Issue by ghankerson** [php-vcr/php-vcr#115]
When using https://github.com/rmccue/Requests and php-vcr  I get errors like this:
`Requests_Exception: Missing header/body separator`

```
vendor/rmccue/requests/library/Requests.php:550
vendor/rmccue/requests/library/Requests.php:329
vendor/rmccue/requests/library/Requests.php:199
```

I have `\VCR\VCR::turnOn();`  in my tests boostrap.php  wondering if you can point me in the right direction

**Comment by ghankerson** [comment]
To give more detail this works fine for me: 
  ```public function testAAA() {
    \VCR\VCR::turnOn();
    \VCR\VCR::insertCassette('apple');
    $result = file_get_contents('http://www.apple.com');
    $this->assertFalse(empty($result));
    \VCR\VCR::eject();
    \VCR\VCR::turnOff();
  }```

While this which call an internal api with the requests library throws the errors outlined above:
`Requests_Exception: Missing header/body separator`

**Comment by adri** [comment]
Thanks, when fixing this issue I noticed that I get [other errors](https://github.com/rmccue/Requests/issues/157) using rmccue/Requests. I would like to wait until that issue is solved and the integration tests work until I merge the php-vcr fixes.

Until then you can try to switch to the fixed branch, in your `composer.json`:
```
"php-vcr/php-vcr": "dev-requests-integration"
```

**Comment by ghankerson** [comment]
super!  @adri    thnaks so much will try this tomorrow.  Very excited about it

**Comment by adri** [comment]
No problem. Thank you for using php-vcr!

**Comment by JeroenVanOort** [comment]
I think this has been fixed by now.
