### ISSUE TITLE
PHP VCR not sending request body

### ISSUE THREAD

**Issue by justincy** [php-vcr/php-vcr#120]
When PHP VCR is enabled the request bodies don't get sent on a POST even though the `Content-Length` header is set and it correctly records the body.

**Comment by justincy** [comment]
I can't figure out what's wrong from debugging and examining the source code. However I do see that POST is not actually tested in integration tests.

**Comment by adri** [comment]
Some questions: 
What is the content of the POST body when you send it? 
What HTTP library are you using?

**Comment by adri** [comment]
Thank you Justin for fixing this in #122. Is your original issue solved?

**Comment by justincy** [comment]
Yes. Thanks.
