### ISSUE TITLE
Duplicate response headers are being dropped

### ISSUE THREAD

**Issue by justincy** [php-vcr/php-vcr#123]
Duplicate response headers are [allowed under certain conditions](http://stackoverflow.com/questions/4371328/are-duplicate-http-response-headers-acceptable). Duplicate values are dropped by PHP VCR (actually, all but the last value are lost).

**Comment by adri** [comment]
Indeed I wasn't aware of that. Thank you. 
The related code would be https://github.com/php-vcr/php-vcr/blob/master/src/VCR/Util/HttpUtil.php#L21 and https://github.com/php-vcr/php-vcr/blob/master/src/VCR/Util/HttpUtil.php#L84.

I'm thinking of switching to PSR 7 for Request and Response, maybe there are some tools already which parse and write headers etc.

**Comment by justincy** [comment]
I'm in the process of fixing this issue :). We won't have to wait for
switching to PSR 7.
