### ISSUE TITLE
Please support dataProviders with VCR

### ISSUE THREAD

**Issue by purpleD17** [php-vcr/php-vcr#126]
Maybe I'm wrong, but it appears data providers don't work with VCR. For example we have a test like this:

```
    function provider_test_call_url() {
        return array(
            array( 'http://www.url1.com', true ),
            array( 'http://www.url2.com', true ),
            array( 'http://www.url3.com', true ),

        );
    }

    /**
     * @vcr test-call-url-result.json
     * @dataProvider provider_test_call_url

     */
    function test_call_url( $url, $result ) {
    ...
    }
```

It seems to totally ignore vcr, not trying to record any cassettes. I'm guessing vcr doesn't know how to run the test 3 times and setup a vcr cassette file for each one of these three calls for the spec.

**Comment by purpleD17** [comment]
By the way, I'm sort of new to open source projects, so if the expectation is for me to submit a PR for this, it's possible, but its probably a pretty big change and will take me a while to learn the code to do so.

**Comment by alnorth** [comment]
I think this was fixed here: https://github.com/php-vcr/phpunit-testlistener-vcr/pull/12. We can probably close this issue.

**Comment by JeroenVanOort** [comment]
As this issue hasn't seen activity for some time, I'm assuming this has been fixed and will close this issue.
