### ISSUE TITLE
Laravel with Guzzle and VCR

### ISSUE THREAD

**Issue by tonywong625** [php-vcr/php-vcr#131]
Hey guys,

I am trying to use VCR to store Guzzle request in my Laravel project. I tried a few ways to get it working however I am running into issues.

I am using Guzzle 6 with Laravel 5 and VCR on dev-master.

1) In my test file I added the simple setup for VCR and it is working!
```
        VCR::turnOn();
        VCR::insertCassette('test.yml');

        file_get_contents('http://www.google.com');

        VCR::eject();
        VCR::turnOff();
```

2) Calling a method in an Abstract class, the cassette (test.yml) is empty
```
        VCR::turnOn();
        VCR::insertCassette('test.yml');

        $response = $this->flights->results($this->searchData);

        VCR::eject();
        VCR::turnOff();
```

3) Adding \VCR\VCR::turnOn(); in tests/autoload.php I get an error with please insert cassette. So I added \VCR\VCR::insertCassette('test'); and it seems to be recording every request into test which is not the best way to store it.

Am I doing anything wrong?

Thanks

**Comment by adri** [comment]
Thanks Tony. Could you please try adding the following to `tests/autoload.php`?

```
\VCR\VCR::turnOn();
\VCR\VCR::turnOff();
```

**Comment by tonywong625** [comment]
Hey Adri,

Thanks for the quick replay and yes that worked well for me.

Thanks
Tony
