### ISSUE TITLE
Looking for co-maintainers

### ISSUE THREAD

**Issue by adri** [php-vcr/php-vcr#142]
As you probably notice, my response time to issues is rather late ;) I don't like it but there are other things which are important to me. 

If anyone likes to help maintaining this repository, please let me know. I'm still around as usual, but I think we can improve the situation by having more maintainers.

**Comment by castarco** [comment]
I think I could be a co-maintainer. I haven't a lot of time, but I need to ensure that this library works perfectly.

My main problem is that I'm not yet familiarized with its internal behavior because its quite complex.

**Comment by adri** [comment]
@castarco Thanks, any help would be greatly appreciated. You need to ensure that this library works perfectly? That is a very admirable goal. One way could be to write more tests, especially for edge cases. This could be a good way to learn more about the internals?

The complexity of this project comes from the low-level intercepting of curl and soap. Those, especially curl, are complex libraries with many options and use-cases. I'd love to find a way to reduce this complexity. When creating php-vcr I explored many ways to do this in PHP and found this to be the best at the time. I'm open to new approaches.

**Comment by aleksandrlat** [comment]
Hello guys,
I created pull request few days ago. Do you still maintain project?
I see there is batch of pull requests.

**Comment by castarco** [comment]
Hi aleksandriat, almost all the pull requests are breaking the automated unit tests, this is the reason we aren't merging them.

**Comment by JeroenVanOort** [comment]
While we're still looking for co-maintainers, having a separate issue for just that seems unneeded.
