### ISSUE TITLE
yaml segfault

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [php-vcr/php-vcr#156]
yaml not working on some cases.
example

`

```
/**
 * @test
 */
public function besttyres()
{

    \VCR\VCR::configure()
            ->setStorage('yaml');

    // After turning on the VCR will intercept all requests
    \VCR\VCR::turnOn();

    // Record requests and responses in cassette file 'example'
    \VCR\VCR::insertCassette('best-tyres');

    $result = file_get_contents("https://www.best-tyres.ru/");

    $this->assertNotEmpty($result);

    // To stop recording requests, eject the cassette
    \VCR\VCR::eject();

    // Turn off VCR to stop intercepting requests
    \VCR\VCR::turnOff();
}
```

`

if i switch to json - works ok.
if i switch to other website - works ok.

but this exect test give me: 

`
PHPUnit 4.8.24 by Sebastian Bergmann and contributors.

...[1]    6124 segmentation fault  vendor/bin/phpunit
`

versions: 

```
        "name": "php-vcr/php-vcr",
        "version": "1.2.8",
        "name": "phpunit/phpunit",
        "version": "4.8.24",
        "name": "laravel/framework",
        "version": "v5.2.31",
```

**Comment by renatomefidf** [comment]
@Vasiliy-Bondarenko thanks for checking on this!
It looks like to be related to special chars, have you tried to investigate more about this?

Since we use symfony yml this could be a bug there!
If you have checked more I would gladly run some tests here as well!

Thank you

**Comment by Vasiliy-Bondarenko** [comment]
@renatomefidf no, i did not. i gave up trying to make it work as i need. 
but "https://www.best-tyres.ru/" - is real website, so may be the bug is still reproducible with it.

**Comment by aaa2000** [comment]
See documentation http://php-vcr.github.io/documentation/configuration/#Storage

Warning: Using the YAML storage could lead to a segmentation fault for large requests or responses. The problem could be fixed by increasing pcre.backtrack_limit in php.ini or by the use of the JSON storage.

**Comment by aaa2000** [comment]
See documentation http://php-vcr.github.io/documentation/configuration/#Storage

Warning: Using the YAML storage could lead to a segmentation fault for large requests or responses. The problem could be fixed by increasing pcre.backtrack_limit in php.ini or by the use of the JSON storage.
