### ISSUE TITLE
[Util/Streamprocessor] PHP file detection

### ISSUE THREAD

**Issue by lapistano** [php-vcr/php-vcr#16]
Currently the Steamprocessor does not recognize files other than those using »php« as file extension as a PHP file and therefore will not process its' contents probably to be replaced in order to make it possible to intercept a request and/or response.

Common extensions for a PHP file might also be:
*.inc
*.php(\d?)  //like *.php4 or *.php5
*.phtml
*.cgi
- ...

**Comment by dbu** [comment]
can't you provide something to register a custom callback function for this decision?

**Comment by JeroenVanOort** [comment]
I think it would be safe to conclude this is no longer needed.
