### ISSUE TITLE
First response header gets lost

### ISSUE THREAD

**Issue by x-yuri** [php-vcr/php-vcr#182]
https://github.com/php-vcr/php-vcr/blob/1.3.1/src/VCR/Util/CurlHelper.php#L60-L61
```php
            $headerList = array(HttpUtil::formatAsStatusString($response));
            $headerList += HttpUtil::formatHeadersForCurl($response->getHeaders());
```
First line creates an array with status code line. Second line adds headers to the array. But first header doesn't get put into the array. Since element with index `0` already exists.

**Comment by librarywebchic** [comment]
I'm seeing this same issue.

**Comment by ejunker** [comment]
Seeing the same issue. It is due to the use of `+=` to combine the arrays.

This example shows that when using `+` to combine arrays with numeric indexes that the first element of the second array is lost.
```php
>>> ['status code'] + ['location', 'length'];
=> [
     "status code",
     "length",
   ]
```

You can use `array_merge()` instead and it fixes the issue.

```php
$headerList = array_merge($headerList, HttpUtil::formatHeadersForCurl($response->getHeaders()));
```
