### ISSUE TITLE
If `opcache` is enabled, VCR hooks may silently fail to work

### ISSUE THREAD

**Issue by RichardBradley** [php-vcr/php-vcr#195]
I have a CI server running my `phpunit` tests, which use PHP-VCR.

On that machine, I have:
```
opcache.enable = 1
opcache.enable_cli = 0
```

I am finding that PHP-VCR is not successfully installing the Curl hook unless I add 

    ini_set('opcache.enable', 0);

to my `tests.bootstrap.php`.

(I am running `phpunit` from the command-line, so I can't work out why the opcache is running here, but it definitely is. I have added logging to the "CurlCodeTransform" class, and it does not see the Guzzle "CurlHandler.php" file unless I add `ini_set('opcache.enable', 0)`.)

I think that PHP-VCR should warn if you use a "`AbstractCodeTransform`" based hook and opcache is enabled, as there is a good chance that things will then silently fail. 

Perhaps the `AbstractCodeTransform::enable()` function should call "`ini_set('opcache.enable', 0)`"?

**Comment by hectorj** [comment]
Can confirm, just got the same issue. Thanks for the workaround :+1:

**Comment by JeroenVanOort** [comment]
This will be fixed in version 1.5.
