### ISSUE TITLE
Segfault regardless of YAML or JSON storage methods.

### ISSUE THREAD

**Issue by BrandonLegault** [php-vcr/php-vcr#196]
I'm getting this error when trying to create a cassette in phpStorm.

`Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)`

I'm using Intuit's QuickBooks Online php SDK to query their REST API for some data in my QuickBooks company. The REST API is OAuth based and their SDK uses php's `OAuth` object internally to GET some data. My wrapper library on their SDK works without issue.

The problem occurs on the return statement in `StreamWrapperHook.php` in the `stream_open()` function. I can't trace it any further than that, assuming because it's being called from an internal php method.

I have a few API calls that need to be made for this particular cassette and, what's interesting about this, the cassette gets created with the proper data from one call before the segfault and then wont perform any of the other calls. If I change the order of the API calls, the result is the same.

Changing the storage method between YAML and JSON has no effect.

**Edit:** Where does the cassette actually get created once the URL hook is executed?

**Comment by JeroenVanOort** [comment]
I'm closing this issue because it has not seen any activity for many years. If anyone feels this is still a problem, please open a new issue.
