### ISSUE TITLE
Broken image in README.md caused by Dropbox's Public Folder changes.

### ISSUE THREAD

**Issue by angyvolin** [php-vcr/php-vcr#197]
As of March 15, 2017 the [Public folder in your Dropbox account has been converted into a standard folder](https://www.dropbox.com/help/files-folders/public). By default this folder is private to your account.

It seems like broken image link in `README.md` is caused by those changes. This can be easily fixed using the [following steps](https://www.dropbox.com/help/files-folders/view-only-access):

1. [Sign in to dropbox.com](https://www.dropbox.com/login).
2. Hover your cursor over the file or folder you'd like to share and click `Share` when it appears.
3. If a link hasn't been created, click `Create a link`. If a link was already created, click `Copy link`.
4. The link will be copied to your clipboard. You can then replace the broken link in `README.md` with that new public-accessible one.

**Comment by JeroenVanOort** [comment]
This has since been fixed: https://github.com/php-vcr/php-vcr/commit/5797258777e6581373152688e7ec6148f5ee6e08#diff-04c6e90faac2675aa89e2176d2eec7d8
