### ISSUE TITLE
Implement fsockopen() interception?

### ISSUE THREAD

**Issue by adri** [php-vcr/php-vcr#20]
[fsockopen](http://www.php.net/manual/en/function.fsockopen.php) communicates directly using the created socket connect. Overwriting `fsockopen()` calls with a `StreamProcessor` and creating an intercepting implementation should be possible. Any need for that?

**Comment by JeroenVanOort** [comment]
As this has been open since 2013 without comments or references, I think it is safe to conclude there is no need.
