### ISSUE TITLE
Not implemented: CURLINFO_TOTAL_TIME

### ISSUE THREAD

**Issue by Schweppesale** [php-vcr/php-vcr#202]
Hey, so I had just came across this bug when i noticed that PHP-VCR is not actually storing any of the following data inside the recorded fixtures:

http://php.net/manual/en/function.curl-getinfo.php

**Comment by stijink** [comment]
I have the same issue here.

**Comment by higidi** [comment]
All curl infos should be implemented since we persist the curl_info with the recordings in #300
