### ISSUE TITLE
Has php-vcr been abandoned?

### ISSUE THREAD

**Issue by alnorth** [php-vcr/php-vcr#209]
Hi guys,

Has this project been abandoned or are you taking a temporary break? I'm happy to help out a little in reviewing pull requests and issues if that would help. php-vcr is a massive help to us.

**Comment by renatomefi** [comment]
Hello @alnorth,

It's kind of a hard timing for the current maintainers, we're working in other projects and php-vcr isn't part of our daily stack in some of the current projects!

Please, feel free to review the PRs and give your opinion, I'll try to stay a bit closer to do a second review, merge and tag.
After you get some knowledge we can make you owner or so!

Thanks for offering help

**Comment by carusogabriel** [comment]
@alnorth For a while, this project took a break. In 2020, some other maintainers and I will work in a new modern `v2` of `PHP-VCR` 😅
