### ISSUE TITLE
Empty cassette file after request

### ISSUE THREAD

**Issue by WishCow** [php-vcr/php-vcr#22]
I'm not sure if I'm using the library incorrectly, but I can't seem to get it to save requests sent with Guzzle:

``` php
$config = VCR::configure();
$config->enableLibraryHooks('curl_rewrite');
$dir = '/srv/http/project/vcr';
$config->setCassettePath($dir);
VCR::turnOn();
VCR::insertCassette('1234');
$client = new \Guzzle\Http\Client();
$rq = $client->post($nlpUrl);
$result = $rq->send();
VCR::eject();
VCR::turnOff();
```

After running this code, a file does appear in in the cassette directory, but it's totally empty.

Am I using the library incorrectly?

**Comment by WillMac29** [comment]
I know this is closed, but I was having an issue similar to this. Turns out it was the process-isolation flag in my phpunit.xml. VCR for whatever reason wanted process-isolation to be set to false.
