### ISSUE TITLE
phpunit --filter=...

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [php-vcr/php-vcr#234]
I have a very strange behaviour of VCR.
if i run all my tests at once with phpunit - it's ok, responses are read from fixtures. 
but if i run only 1 of this tests separately with 
phpunit --filter=check_new_blocks_command
VCR tries to read from the network instead of fixtures. how can it be possible??? i'm lost. :)

the test looks like this:
```php
    /** @test */
    public function check_new_blocks_command()
    {
        \VCR\VCR::turnOff(); // just in case.
        \VCR\VCR::turnOn();
        \VCR\VCR::configure()->setCassettePath(base_path("tests/fixtures"));
        \VCR\VCR::insertCassette('check_new_blocks_command');

        // action ...

        $this->stopVcr();
    }
```

**Comment by renatomefi** [comment]
@Vasiliy-Bondarenko I think I've see this happening before.

Sadly I don't have the time to check, would you like to debug and please if possible submit a fix for us? I'll glad to test it in case you find something!

**Comment by JeroenVanOort** [comment]
This works fine in now. If this occurs once more, please open a new issue referencing this one.
