### ISSUE TITLE
Does not open stream with code that generate salt by file_get_contents('/dev/urandom', false, null, 0, 16)

### ISSUE THREAD

**Issue by penja** [php-vcr/php-vcr#239]
Hi.
Thanks for this awesome library.

When using PHP VCR with code that use `file_get_contents('/dev/urandom', false, null, 0, 16)` for generating pseudo random salt. VCR recorder do not open the stream. We have got error like this:
``` 
file_get_contents(/dev/urandom): failed to open stream: "VCR\Util\StreamProcessor::stream_open" call failed
```

**Comment by killua99** [comment]
Did you fix this issue?

**Comment by renatomefi** [comment]
Please update to v1.4.3

**Comment by sithara** [comment]
This seems to be still breaking for me when I try to open a local file using file_get_contents in my `phpunit` tests. Appreciate any help

**Comment by renatomefi** [comment]
@sithara what's the version you have installed? The version 1.4.3 is still marked as pre-release for testing, so you might have to force it on you composer.json

**Comment by sithara** [comment]
My `php-vcr` version is `1.3.2` . I'm also getting very weird errors like https://github.com/php-vcr/php-vcr/issues/251 . It works correctly if its the cassette is set to record file_get_contents('http://www.google.com') . In my case, I have a `curl_exec` posting file contents to a server. Not sure where I'm going wrong

**Comment by renatomefi** [comment]
@sithara so please first update to 1.4.3 and try again
