### ISSUE TITLE
Not working for Behat tests in Drupal 8

### ISSUE THREAD

**Issue by bkosborne** [php-vcr/php-vcr#253]
I wonder if anyone has this library working for writing behat tests in Drupal 8? I'm using the version 1.4.4 of this library and my own fork of the [https://github.com/bkosborne/behat-vcr-extension](behat vcr extension) (so I could incorporate a bug fix and allow a version bump of this library).

I just get blank cassette files, which I think indicates that this library's replacement curl functions are not being called. I'm trying to test some pages on my site that make Guzzle requests, which it seems like should be fine, since Guzzle is using curl under the hood.

I read in another issue that the VCR must be 'started' right away after the autoloader, but I'm not sure if that's really the case anymore? In the various VCR extension libraries I've seen, none of them do that, they just turn it on when it's needed.

In any case, when I try to turn it on in my index.php right after the autoloader, I get a Drupal error about it being unable to locate another class that it needs for database interactions (not sure why).

**Comment by moufmouf** [comment]
Hey @bkosborne ,

Your issue might be related to an Opcache issue I've been facing.
Basically, if your PHP files are loaded into Opcache and if you enable PHP-VCR after that, PHP-VCR will not be able to "instrument" the PHP files and injects its code in those.

#254 will fix this when merged. It might be a good idea to retest PHP-VCR when this is merged.

**Comment by JeroenVanOort** [comment]
Please retest when 1.5.0 is released, as it will contain the opcode fix.
