### ISSUE TITLE
Is Possible To Configure PHP VCR to Work With Laravel Dusk?

### ISSUE THREAD

**Issue by taufek** [php-vcr/php-vcr#265]
I wish to run [Laravel Dusk](https://github.com/laravel/dusk) tests while mocking all external requests. Is this possible to use PHP VCR and Laravel Dusk to achieve this?

**Comment by renatomefi** [comment]
Hello @taufek 
I've never used Dusk, maybe you can just try it and see how it works? VCR should be invisible to Dusk in that sense.
Please try and let us know, thanks!

**Comment by JeroenVanOort** [comment]
PHP-VCR can not work with browser tests, regardless of the package you use. That's because the test code and the application code are executed separately.

Yes, that's annoying at time, but not something we can do anything about.
