### ISSUE TITLE
Abstract Code Transform Splits In Middle Of File

### ISSUE THREAD

**Issue by bassrock** [php-vcr/php-vcr#268]
When trying to use PHP-vcr with the stripe api it turns out that the [filter function](https://github.com/php-vcr/php-vcr/blob/master/src/VCR/CodeTransform/AbstractCodeTransform.php#L50) happens to split the code file right in the middle of the curl statement at this line: 

https://github.com/stripe/stripe-php/blob/master/lib/HttpClient/CurlClient.php#L253

This causes php-vcr to not properly replace the curl_setops_array function and hence causing php-vcr to fail for the stripe api.  I tried a few different ways to fix this but they felt like hacks and you can not currnetly add your own code transformers.

**Comment by higidi** [comment]
See https://github.com/php-vcr/php-vcr/pull/269#issuecomment-1355137112
