### ISSUE TITLE
SoapCodeTransform

### ISSUE THREAD

**Issue by janvernieuwe** [php-vcr/php-vcr#282]
When there is a class that extends for example a `MySoapClientBuilder` it will be replaced with  `extends \VCR\Util\SoapClientBuilder` which doesn't exist and causes the client to be untestable while using php-vcr.

This happens in the `SoapCodeTransform`, I think the second pattern regex could be improved to prevent this kind of behavior.

**Comment by JeroenVanOort** [comment]
Thank you for your contribution! I've just merged the PR.
