### ISSUE TITLE
Revamp PHP-VCR

### ISSUE THREAD

**Issue by carusogabriel** [php-vcr/php-vcr#292]
Alright, after a while PHP-VCR is back in the game 💪🏻

As we have new maintainers, the goal is to revamp and modernize this project in its version `2.0` 🎉 

We'll take a look into the open PRs and get familiar with the codebase so we can start to merge and improve some stuff 🛠

Main ideas for now 💡 

- Require minimum PHP 7.2 (as proposed in #259 by @moufmouf)
- Require Symfony 5 (as proposed in #287 by @Jeroeny)
- Introduce a Static Analysis tool (as proposed in #257 by @moufmouf)
- Make usage of a [Makefile](https://www.cs.usask.ca/staff/oster/makefiles.html) instead of Composer scripts

After that, we can start to take a look into bug fixes and new features ☺️

**Comment by carusogabriel** [comment]
The development of this new version will happen in the [`2.x branch`](https://github.com/php-vcr/php-vcr/tree/2.x).

**Comment by janvernieuwe** [comment]
Hell yeah <3
I'll look into contributing.

**Comment by clemherreman** [comment]
Yey, couldn't be happier to see this project will have new people maintaining it. Thank you for stepping up <3

A couple of feedback, about that roadmap:

* Requiring only Symfony 4.4 allows more people to move to that 2.0 version, as any 4.x version will be ok.
* What do you feel about maintaining (a little) the 1.x version? I personnally have some simple PR waiting for merge, and I would gladly help review/merge the other one waiting, or at least the one where the contributor is still active :)

Thank you for your time! :)

**Comment by moufmouf** [comment]
Excellent news!

I've spent quite some time last year working on modernizing the PHP codebase (in #259 as you noted).
Tell me if you need some help :)

**Comment by carusogabriel** [comment]
@moufmouf My idea is to use your code/commits instead of trying something from scratch :)

**Comment by carusogabriel** [comment]
> Requiring only Symfony 4.4 allows more people to move to that 2.0 version, as any 4.x version will be ok.

@clemherreman We can go for 4.4, as it'll be maintained for a while: https://symfony.com/releases#checker.

> What do you feel about maintaining (a little) the 1.x version? I personnally have some simple PR waiting for merge, and I would gladly help review/merge the other one waiting, or at least the one where the contributor is still active

We can consider that. I'll take a look into the PRs/issues.

**Comment by janvernieuwe** [comment]
Having 4.4 supported in version 1 would also be fine, and having SF5 in v2.
The only thing is that something really needs to happen, as it is now, php-vcr is not usable with php 7.4 or with SF5 (Both things I use).

I have already resorted to a private fork to have the 7.4 fixes working, and did a few tweaks, I'd rather have all those in the main repo ofcourse!

**Comment by clemherreman** [comment]
> I have already resorted to a private fork to have the 7.4 fixes working, and did a few tweaks, I'd rather have all those in the main repo ofcourse!

I tried to update to Symfony 4.4, but I was stuck because some things symfony/http-client uses in cURL are not supported by PHP-VCR. 

I also have a fork, and did some PR back to PHP-VCR to fix some of those, but not all. By any chance, could you make your fork public? :)

**Comment by janvernieuwe** [comment]
> > I have already resorted to a private fork to have the 7.4 fixes working, and did a few tweaks, I'd rather have all those in the main repo ofcourse!
> 
> I tried to update to Symfony 4.4, but I was stuck because some things symfony/http-client uses in cURL are not supported by PHP-VCR.
> 
> I also have a fork, and did some PR back to PHP-VCR to fix some of those, but not all. By any chance, could you make your fork public? :)

We're currently looking into alternatives with http client middlewares.
The private fork contains changes made for the company I work for, so I cant easily make it public.

I had it working on SF 4.4 with guzzle tho, just by fixing the 7.4 bug.

**Comment by carusogabriel** [comment]
I'm sorry to inform you all but I won't be able to work on `php-vcr` anymore due to personal reasons.

I've contacted the maintainers and they'll find someone else to maintain this package.

**Comment by janvernieuwe** [comment]
Sorry to hear that, but I thank you for your efforts so far!
Also thanks for communicating this clearly.

**Comment by JeroenVanOort** [comment]
I'm willing to help out where I can. How do I get involved?

**Comment by JeroenVanOort** [comment]
1.5.0 has been released, solving most if not all things discussed in this issue.
