### ISSUE TITLE
The JSON storage is slow and unnecessarily CPU-consuming

### ISSUE THREAD

**Issue by morozov** [php-vcr/php-vcr#296]
I have a test where the VCR intercepts 3 HTTP requests totaling ~1MB. Given that the corresponding responses are cached, I’d expect the test to pass in fractions of a second but it takes about 6 seconds.

![callgraph](https://user-images.githubusercontent.com/59683/74051055-1a142b80-498c-11ea-84f1-d7591aafbc98.png)

The reason is that the JSON storage is implemented in a memory-efficient way and reads the stored JSON _byte-by-byte_ using `fgets()`:
https://github.com/php-vcr/php-vcr/blob/41f532155456521a80d66801b09ecba994f9d004/src/VCR/Storage/Json.php#L55

The potential solutions that come to mind are:
1. Keeping the current design, implement a read buffer and instead of matching characters one-by-one, use a regex-based approach (see https://github.com/doctrine/dbal/pull/2495 for example).
2. Reimplement the storage using a 3rd-party streaming JSON parser like [salsify/jsonstreamingparser](https://github.com/salsify/jsonstreamingparser) (will probably require bumping the minimal supported PHP version which is AFAIK already planned).

**Comment by morozov** [comment]
In addition to the performance problem, there is a problem with parsing stored JSON: the actual request/response bodies are parsed as JSON too that may create issues like the following:
```php
public function testIterateStringWithCurlyBraces()
{
    $this->iterateAndTest(
        '[{"para": "}:->"}]',
        array(
            array('para' => '}:->'),
        )
    );
}

// 1) VCR\Storage\JsonTest::testIterateStringWithCurlyBraces
// Failed asserting that two arrays are equal.
// --- Expected
// +++ Actual
// @@ @@
//  Array (
// -    0 => Array (...)
// +    0 => null
//  )
```

**Comment by matt-allan** [comment]
I'm not positive but a [JSON streaming format](https://en.wikipedia.org/wiki/JSON_streaming) would probably be more efficient to parse since you could read the entire object with a single function call.

**Comment by morozov** [comment]
@matt-allan it would but it turns out to be overkill. We don't really need to _parse_ the body at all. We need to make sure we parse the envelope properly. See the PR above.
