### ISSUE TITLE
PHP VCR is not supporting Laravel 7.0

### ISSUE THREAD

**Issue by ibsrini** [php-vcr/php-vcr#303]
We are using php-vcr in Laravel 6.0. Trying to upgrade 7.0 and getting below error.
- symfony/event-dispatcher v2.6.0 conflicts with symfony/console[v5.0.8].

Below packages needs to update latest version and support.
"symfony/yaml": "~2.1|^3.0|^4.0",
"symfony/event-dispatcher": "^2.4|^3.0|^4.0"

I have tried to fetch latest versions like below
"symfony/yaml": "~2.1|^3.0|^4.0|^5.0",
"symfony/event-dispatcher": "^2.4|^3.0|^4.0|^5.0"

But VCR http calls getting failed. Can anyone check this?

**Comment by JeroenVanOort** [comment]
I would suggest adding support for Symfony 5 to PHP-VCR, as that is what is the core problem.

**Comment by ibsrini** [comment]
Yes, support for Symfony 5 is main problem with PHP 7.3. 

For upgrade PHP-VCR is not working on PHP 7.4.

Regards,
Srini

**Comment by JeroenVanOort** [comment]
Resolved by https://github.com/php-vcr/php-vcr/issues/320 in 1.5.0.
