### ISSUE TITLE
BadMethodCallException: Not implemented: CURLINFO_APPCONNECT_TIME (3145761) 

### ISSUE THREAD

**Issue by ibsrini** [php-vcr/php-vcr#309]
When I run the test, it throws the error
BadMethodCallException: Not implemented: CURLINFO_APPCONNECT_TIME (3145761) 

and the file path is
/php-vcr/php-vcr/src/VCR/Util/CurlHelper.php:131

**Comment by JeroenVanOort** [comment]
Could you give some more information? Like the PHP version and what test you're running exactly. It helps to recreate the circumstances.

**Comment by ibsrini** [comment]
Hi, I have using it on PHP 7.3
If I make HTTP call to external servers, I am getting the errors.
<img width="845" alt="Screen Shot 2020-06-16 at 10 48 32 PM" src="https://user-images.githubusercontent.com/64610028/84860262-9944fa80-b023-11ea-82b4-e6b3c9ac8595.png">

**Comment by JeroenVanOort** [comment]
Which versions of curl and php-vcr are you running?

**Comment by ibsrini** [comment]
I am using macOS Catalina 10.15.5
**Curl version:**
curl 7.70.0 (x86_64-apple-darwin19.4.0) libcurl/7.70.0 SecureTransport zlib/1.2.11
Release-Date: 2020-04-29
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile libz NTLM NTLM_WB SSL UnixSockets

php-vcr - 1.4 with fix of event-dispatcher & symfony 5.0

**Comment by avrahamappel** [comment]
Getting a similar error:
```
ErrorException:  Undefined offset: 3145761
at vendor/php-vcr/php-vcr/src/VCR/Util/CurlHelper.php:115
```
php-vcr/php-vcr: 1.5.0alpha1
guzzlehttp/guzzle: 6.5.5 (was working before I switched to Guzzle from raw curl)
php: 7.4.8
curl: 7.64.1 (x86_64-apple-darwin19.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2
macOS Catalina 10.15.5

**Comment by igaster** [comment]
I get the same error:

```
  ErrorException: Undefined offset: 3145761
```

I could trace the error into Guzzle client here:  [Guzzle::CurlFactory()](https://github.com/guzzle/guzzle/blob/c19f9e2493942634f740e7bed5c6a9f85cc19453/src/Handler/CurlFactory.php#L131). If I comment this line then it works fine.

PHP constant `CURLINFO_APPCONNECT_TIME` has a value of `3145761` and it is described in [php documentation](https://www.php.net/manual/en/function.curl-getinfo.php)

I am switching from Guzzle, to Laravel which has a native HTTP client  (which is essentially a Guzzle wrapper). I assume that Laravel is adding some configuration to guzzle client that introduces the error.

My env:

- PHP 7.4.5
- Ubuntu 18.04.4 LTS

Composer:

- guzzlehttp/guzzle: 6.5.5
- php-vcr/php-vcr: 1.5.0alpha1

Error stack:

```
/var/www/html/vendor/php-vcr/php-vcr/src/VCR/Util/CurlHelper.php:115
/var/www/html/vendor/php-vcr/php-vcr/src/VCR/LibraryHooks/CurlHook.php:323
/var/www/html/vendor/php-vcr/php-vcr/src/VCR/LibraryHooks/CurlHook.php:160
/var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:123
/var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:101
/var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php:43
/var/www/html/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php:28
/var/www/html/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php:51
/var/www/html/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php:629
/var/www/html/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php:599
/var/www/html/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php:585
/var/www/html/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php:37
/var/www/html/vendor/guzzlehttp/guzzle/src/Middleware.php:35
/var/www/html/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php:70
/var/www/html/vendor/guzzlehttp/guzzle/src/Middleware.php:57
/var/www/html/vendor/guzzlehttp/guzzle/src/HandlerStack.php:71
/var/www/html/vendor/guzzlehttp/guzzle/src/Client.php:351
/var/www/html/vendor/guzzlehttp/guzzle/src/Client.php:162
/var/www/html/vendor/guzzlehttp/guzzle/src/Client.php:182
```

**Comment by matt-allan** [comment]
I believe this happens with the Laravel HTTP client because it uses the [`on_stats` Guzzle option](http://docs.guzzlephp.org/en/stable/request-options.html#on-stats). The `on_stats` option tries to call `curl_getinfo($h, \CURLINFO_APPCONNECT_TIME)`, and that fails because VCR can't mock all of the `curl_getinfo` options.

To reproduce this you can record a fixture using the curl hook that calls `curl_getinfo($h, \CURLINFO_APPCONNECT_TIME)`, then try to replay the fixture.

I'm pretty sure this happens because VCR [only allows returning values defined in the `curlInfoList`](https://github.com/php-vcr/php-vcr/blob/1b152a62f5289373d40eee456992f32abfae144f/src/VCR/Util/CurlHelper.php#L115). However that check shouldn't be necessary anymore because the HTTP Client now saves all of the `curl_getinfo` constants when a fixture is created.

**Comment by oranges13** [comment]
If anyone else finds themselves here, you can find commits in forks that fix this and apply them manually, but I'm also going to submit a PR to do the same to this repo.
