### ISSUE TITLE
fstat call fails for non-altered streams

### ISSUE THREAD

**Issue by endrsmar** [php-vcr/php-vcr#322]
Using PHP-VCR and FPDI together in a test, when an FPDI tries to load a PDF file it crashes. The reason for this is it tries to get the size of an PDF file in one of the methods, but the file stream is wrapped in the PHP-VCR `StreamProcessor` which always returns `false` when asked for `stream_stat` even if the stream is not actually modified by any transformers. I prepared a PR to fix this issue: https://github.com/php-vcr/php-vcr/pull/321

**Comment by JeroenVanOort** [comment]
Not to self: a PR has been made: https://github.com/php-vcr/php-vcr/pull/321

**Comment by endrsmar** [comment]
Is fixed in 1.5
