### ISSUE TITLE
Current master has failing tests

### ISSUE THREAD

**Issue by JeroenVanOort** [php-vcr/php-vcr#332]
As you may have noticed, the current master fails on Travis at this moment. I've already fixed a small phpstan error in my branch `debugging-travis`. But some tests are failing too.

After updating my local environment, I've been able to reproduce the problems with the tests for PHP 7.3 (didn't try, but I don't expect 7.4 to be any different). However, I'm not sure yet what causes these problems and what would be a sensible way to solve them.

I'll look further into this, tomorrow. Please let me know if you have an idea what's going on, even if you're not sure.

**Comment by pvgnd** [comment]
@JeroenVanOort fix proposition here: https://github.com/php-vcr/php-vcr/pull/333

**Comment by specialtactics** [comment]
Thanks for looking into this!
