### ISSUE TITLE
Migrate from Travis to Github actions

### ISSUE THREAD

**Issue by JeroenVanOort** [php-vcr/php-vcr#341]
From what I understand, Travis will stop soon and builds are slow anyway. I'll do my best to work on this myself, but anyone is welcome to open a PR.

If at all possible, I think it would be good if the project's docker file is used for the CI too.

**Comment by dchw** [comment]
I'm willing to help out here! I think I could help speed it up, and incorporate the `Dockerfile` by introducing an [`Earthfile`](https://earthly.dev). Would be willing to see it through if you are game?

**Comment by Justintime50** [comment]
Looks like it's currently in the works: https://github.com/php-vcr/php-vcr/pull/345

**Comment by JeroenVanOort** [comment]
Fixed.
