### ISSUE TITLE
PHP 8.1 Compatibility

### ISSUE THREAD

**Issue by veewee** [php-vcr/php-vcr#360]
While using php-vcr, some deprecations pop up.
Example:

- Deprecated: Return type of VCR\Storage\Yaml::valid() should either be compatible with Iterator::valid(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
- Deprecated: Return type of VCR\Storage\AbstractStorage::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

**Comment by Justintime50** [comment]
I too would like to see this fixed. I'm open to putting up a PR but see there are a bunch of unmerged PRs from years passed and am hesitant to do the work if it won't get merged.

**Comment by etienneleba** [comment]
UP, I need it too, is the project still alive ? I see a lot contributions but no one to merge...

**Comment by Xusifob** [comment]
That would be great indeed

Is the owner open for new maintainers to take over the project / Help with PR & Issues ?

**Comment by Justintime50** [comment]
Nothing about that PR was a breaking change? If following semantic versioning it should just be a patch version bump since things are being *fixed*.

1.6 should have definitely been 2.0 though

**Comment by higidi** [comment]
Sound good for me, 1.6.2 is definitely a better choice then 1.7, you're right, because 1.6 already had the BC changes which will now be fixed! Will be released in a few minutes.
