### ISSUE TITLE
BadMethodCallException: Not implemented: CURLINFO_EFFECTIVE_URL (1048577) 

### ISSUE THREAD

**Issue by whikloj** [php-vcr/php-vcr#363]
In a curl multihandle I use this curlinfo option to get the current handle's URL. It appears relatively easy to fix, but I'm also very new to php-vcr.

**Comment by higidi** [comment]
As announced in #413 i'll create a new patch to support `CURL_EFFECTIVE_URL`.

**Comment by higidi** [comment]
Ok, i didn't unterstand why we should do that. With pr #300 we also persist the curl info array (also the `url` which is to be the `effective_url`) so it should be also respond to `CURLINFO_EFFECTIVE_URL`.
What you've done is to always respond always with request url, which might differ from the effective url. So i didn't understand the benefit. Is this meant as a kind of fallback?

**Comment by higidi** [comment]
Closed because no answer
