### ISSUE TITLE
compatibility Symfony 6 (YAML v6)

### ISSUE THREAD

**Issue by medhki** [php-vcr/php-vcr#367]
Installing the package for a symfony 6 project:
 **php-vcr/php-vcr 1.6.0 requires symfony/yaml ^3.0|^4.0|^5.0 -> found symfony/yaml[v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.37, v5.0.0, ..., v5.4.3] but it conflicts with your root composer.json require (6.0.*)**

**Comment by specialtactics** [comment]
Hey guys feel free to use our fork, we're a company so we will likely look after this package for some time.
https://github.com/CoverGenius/php-vcr

**Comment by higidi** [comment]
Resolved via #361
