### ISSUE TITLE
Error: Typed property VCR\Response::$httpVersion must not be accessed before initialization

### ISSUE THREAD

**Issue by Justintime50** [php-vcr/php-vcr#395]
Updated to v1.6.6 using PHP 8.2.0 (also tried 8.1.23) on Linux and receiving the following:

```
Error: Typed property VCR\Response::$httpVersion must not be accessed before initialization
```

Didn't seem to get this error before the update.

**Comment by higidi** [comment]
Ok, update phpstan and phpcs in #392 i'll fix it.

**Comment by Justintime50** [comment]
That seemed to do the trick, thank you for the quick turnaround!
