### ISSUE TITLE
Curl malformed url

### ISSUE THREAD

**Issue by matjack1** [php-vcr/php-vcr#63]
Hello,
I'm trying to use php-vcr which will improve a lot the testability of our system, but I have a problem.
I get this error which I cannot understand:
```Guzzle\Http\Exception\CurlException: [curl] 3: <url> malformed [url]```
I'm testing an interaction with Amazon SQS in a Yii/PHPunit test suite.

I'm starting php-vcr in the ```bootstrap.php``` file like so:
```
\VCR\VCR::configure()->setCassettePath('fixtures');
\VCR\VCR::turnOn();
``` 
and then the ```setUpBeforeClass``` is already failing with the error I've said in the beginning.
```
public static function setUpBeforeClass() {
	\VCR\VCR::insertCassette('example');
	self::$helper = new AmazonSQSHelper( 'send-access-stk' );
	parent::setUpBeforeClass();
}
```

I tried to replace the Amazon call with this standard curl code:
```
$ch = curl_init("http://www.example.com/");
$fp = fopen("example_homepage.txt", "w");

curl_setopt($ch, CURLOPT_FILE, $fp);
curl_setopt($ch, CURLOPT_HEADER, 0);

curl_exec($ch);
curl_close($ch);
fclose($fp);
```
and it works fine. Do you have any suggestion on how to understand more about the problem?
Thanks a lot.

**Comment by adri** [comment]
Since the latest master branch, php-vcr itself doesn't depend anymore on Guzzle. It might be, that this error is gone now. I know its been a while ;-) 

If you find some time, please check if this issue can be closed.

**Comment by matjack1** [comment]
Hi @adri thanks! I've tried again and now I've got this error:

```VCR\VCRException: Invalid HTTP status '', expected format like: 'HTTP/1.1 200 OK'.```

I bet is some weirdness in the Amazon library. I don't know if it's worth to keep the issue open :)
Sadly at the moment we cannot upgrade the library so I don't want to blame php-vcr for the problem ;)

**Comment by matjack1** [comment]
@adri I managed to update the Amazon library and it looks like it's recording stuff!
The problem now is that it doesn't replay, maybe because the calls are time related? In all the requests there is a header like this: ```x-amz-date: 20150123T174129Z``` which obviously changes every time. That means I can't use php-vcr in this case?

**Comment by adri** [comment]
Awesome! You can choose what you want the requests to match on, please see "request matching" in the [docs](http://php-vcr.github.io/documentation/configuration/). Does that help?

**Comment by matjack1** [comment]
Ohhhh yes. Thanks a lot!
