### ISSUE TITLE
SoapFault: SOAP-ERROR: Parsing WSDL: Couldn't load from...

### ISSUE THREAD

**Issue by alexlangberg** [php-vcr/php-vcr#64]
I'm trying to use this with:

- phpunit-testlistener-vcr
- Laravel 4.1.29
- PHP 5.5.6 (soap is turned on, have checked in php -i)
- Windows

I have a test which calls a SOAP WSDL with SoapClient. It works fine, until I put this before it:
```PHP
/**
* @vcr unittest_foobar
*/
```
This creates an empty fixture but now the test fails with this:
*SoapFault: SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://api.e-conomic.com/secure/api1/EconomicWebservice.asmx?W
SDL' : failed to load external entity "https://api.e-conomic.com/secure/api1/EconomicWebservice.asmx?WSDL"*

However, I can change the test to instead of a SOAP call just do:
```PHP
$testfile = file_get_contents('http://www.google.com');
```
Now it all works fine and the fixture is created as it should be. Any ideas?

**Comment by adri** [comment]
There was some work on the soap part. If you like, you can test again if fixtures are recorded. I'm closing this issue in favor of #11.
