### ISSUE TITLE
PHP-VCR with behat

### ISSUE THREAD

**Issue by emileswarts** [php-vcr/php-vcr#71]
Hi

Thanks for this library.
I cannot seem to find too much on the subject of using VCR with Behat.

I can get the following to execute and write the recording in Behat:

```
public function iSubmitFeedbackWithValidData()
{
    VCR::turnOn();
    VCR::insertCassette('successful_contact_submit');

    file_get_contents('http://www.google.com');

    VCR::eject();
    VCR::turnOff();
}
```

But this doesn't work:

```
public function iSubmitFeedbackWithValidData()
{
    VCR::turnOn();
    VCR::insertCassette('successful_contact_submit');

    $this->fillInContactForm();
    $this->page()->pressButton('Submit');

    VCR::eject();
    VCR::turnOff();
}
```

Is this a reasonable thing to try and do with php-vcr?

**Comment by adri** [comment]
Actually it would be nice to integrate behat some day as it seems there is a need for it. 
Integrating can get simpler once #86 is merged. I would like to keep this issue open for further references.

**Comment by dbu** [comment]
note that with behat things depend on the test runner. if its a php runner in the same process, starting the recorder should probably just work, right? but when going through selenium and a phantomjs/firefox/whatever browser, a new web request is started and a new php process.

we need to do this in a project (the web requests). we where brainstorming about injecting a custom header to phantomjs (assuming that thats possible) that would identify the behat feature and we would then have the entry code (symfony app_test.php) look for that header.

**Comment by kasperg** [comment]
Perhaps it is worth mentioning [`aaa2000/behat-vcr-extension`](https://github.com/aaa2000/behat-vcr-extension) here. It does not pop up in searches for "behat php-vcr" - this issue does.

**Comment by renatomefi** [comment]
@kasperg indeed, thank you!

**Comment by JeroenVanOort** [comment]
As there is an extension, I think this is no longer an open issue.
