### ISSUE TITLE
Using YML cassette results in "Segmentation fault: 11"

### ISSUE THREAD

**Issue by alexdomsa** [php-vcr/php-vcr#84]
The memory limit set in php.ini on my machine is: memory_limit = 1024M

In the cassette we have a response which contains 163750 characters on a single line. 
When we use JSON format the tests are working as expected, but when YML format is used we end up with "Segmentation fault: 11".

I suspect there is an issue with YmlParser (which is not a component developed by you), so I was wondering why YML is default option, not JSON?

**Comment by tylercollier** [comment]
> The memory limit set in php.ini on my machine is: memory_limit = 1024M

What does that have to do with the line length?

**Comment by alexdomsa** [comment]
It doesn't necessarily have to do anything with line length, but I was thinking that maybe because the line is too long, it loads the entire line in memory.
I just wanted to post some details that might be helpful, related to this bug.

**Comment by adri** [comment]
Added to documentation http://php-vcr.github.io/documentation/configuration/#storage thanks to @aaa2000.
